### ISSUE TITLE
Comprehensiveness

### ISSUE THREAD

**Issue by Daniel-Mietchen** [pkraker/open-discovery#13]
I just saw [this article](http://www.storybench.org/science-search-engine-visualizing-discovery-process/) which stated that you're aiming to be "as comprehensive as possible". Have you considered using output from [ContentMine](https://github.com/ContentMine) for your clustering?

**Comment by pkraker** [comment]
We have already discussed this possibility, but thanks for brining it up again! The multi-view probabilistic topic modeling (MV-PTM) engine that we want to use for clustering and labeling can process all kinds of side information. To quote the proposal "Side information ("views") may be of different kinds (e.g. structured or unstructured attributes and metadata), have hierarchies or taxonomies (e.g. MESH terms), be of different modalities (e.g. images), and form networks (e.g. citations)." Therefore, it would certainly be possible to include facts and taxonomies extracted by ContentMine in BLAZE.
