### ISSUE TITLE
Mapping concepts to Wikidata?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [pkraker/open-discovery#14]
I think it would be great if the concept clouds you are producing would map to Wikidata concepts by default. [StrepHit](https://meta.wikimedia.org/wiki/Grants:IEG/StrepHit:_Wikidata_Statements_Validation_via_References) may be able to help with that.

**Comment by pkraker** [comment]
Yes, that would certainly be very useful. As laid out in my answer to issue #13, our topic modeling engine can deal with all kinds of side information, and we could include Wikidata concepts as well.
